baseURL = "https://ChristianDjurhuus.github.io/DataStoryTelling/"
languageCode = "en-us"
title = "Data Story Telling"
theme = "hugo-theme-stack"


[params]
  author = "Christian Djurhuus"
  description = "A blog exploring various of topics using a data science approach."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ChristianDjurhuus"

  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/christian-djurhuus-08a7b1189?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BQANi4wArQQaEqT0f0uG0Ng%3D%3D"

